use locadora
	create table FILMES	(
	ID_Filme SMALLINT PRIMARY KEY IDENTITY(1,1),
	GENERO varchar(25) NOT NULL,
	DURACAO varchar(25) NOT NULL,
	ANO varchar(20) NOT NULL,
	TITULO varchar(255) NOT NULL
	
	)

	create table FUNCIONARIOS(
		ID_Funcionario SMALLINT PRIMARY KEY IDENTITY(1,1),
		NOME varchar(50) NOT NULL,
		ENDERECO VARCHAR(100) NOT NULL,
		BAIRRO VARCHAR(50) NOT NULL,
		CIDADE VARCHAR(50) NOT NULL,
		UF VARCHAR(3) NOT NULL,
		CEP VARCHAR(100) NOT NULL,
		CPF VARCHAR(100) NOT NULL,
		CARGO VARCHAR(100) NOT NULL,
		SALARIO Float(25) 
		)

	create table CLIENTES (
	ID_Clientes SMALLINT PRIMARY KEY IDENTITY(1,1),
	NOME varchar(50) NOT NULL,
	ENDERECO varchar(50) NOT NULL,
	BAIRRO varchar(50) NOT NULL,
	CIDADE varchar(50) NOT NULL,
	UF varchar(50) NOT NULL,
	CEP varchar(50) NOT NULL,
	CPF varchar(50) NOT NULL
	)

	create table FILMES_LOCACAO (
	ID_Locacao SMALLINT PRIMARY KEY IDENTITY(1,1),
	NUMERO_LOCACAO varchar(50) NOT NULL,
	ID_FILME varchar(50) NOT NULL,
	QTDE varchar(50) NOT NULL, 
	VALOR_LOCACAO varchar(50) NOT NULL
	)

	create table LOCACAO (
	 DATA_RETIRADA date,
	 ID_CLIENTE int,
	 ID_FUNCIONARIO int,
	 STATUS varchar(50)
	 )